name: GitHub Actions - Hello World
on: [push]
jobs:
  Run-Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run Hello World
        run: node index.js